assets.json
devnet/assets.json
mainnet/assets.json
testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/2)

feat: update denom and display name for coreum native token

---

devnet/assets.json
mainnet/assets.json
testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/3)

fix: update paths to coreum logos

---

devnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/4)

feat: add ibc token

---

devnet/assets.json
mainnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/9)

feat: add chain to ibc tokens

---

mainnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/11)

fix links to assets (band&atom)

---

mainnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/12)

fix: update precisions

---

mainnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/13)

fix: precision for BAND token

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/16)

fix: update typo

---

devnet/assets.json
mainnet/assets.json
testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/17)

feat: add denom to extra's ibc info

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/18)

fix: update chain name for osmo in testnet

---

mainnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/22)

feat: remove sei

---

mainnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/23)

fix: update source chain for atom

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/24)

feat: update xrpl originated tokens' denoms for testnet

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/25)

feat: add test token

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/26)

feat: add tokens to testnet with negative sending precision

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/27)

feat: add token to testnet

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/29)

feat: update tokens for testnet

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/30)

feat: add xrpl_info for some testnet assets

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/31)

feat: add xrpl_info for test tokens

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/34)

feat: update testnet tokens

---

testnet/assets.json

Please provide a brief description of the changes you are making in this PR.
Once this PR is merged, your asset will automatically become visible on the respective explorer page:
- **Devnet**: [Explorer](https://explorer.devnet-1.coreum.dev/coreum)
- **Testnet**: [Explorer](https://explorer.testnet-1.coreum.dev/coreum)
- **Mainnet**: [Explorer](https://explorer.coreum.com/coreum)
If you selected Token Bridging your asset will be added to Coreum XRPL Bridge smart contract.
After that is done it will become available for bridging on [Sologenic](https://sologenic.org/bridge/coreum-bridge) or [Pulsara](https://dax.pulsara.io/bridge)
Thank you for contributing to the Coreum Token Registry! 🚀
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Fix json schema for GLO dollar on testnet

---

testnet/assets.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/CoreumFoundation/token-registry/50)

feat: update denom for osmo in testnet
